server:
  port: 8080

#cupSize: B
#age: 18
#content: "cupSize: ${cupSize},age: ${age}"
#
#girl:
#  cupSize: F
#  age: 18


spring:
  profiles:
   active: dev
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/dbgirl?serverTimezone=GMT%2B8
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true